### ISSUE TITLE
Only builds debug version

### ISSUE THREAD

**Issue by rizwindu** [hpcn-uam/libstable-opencl#1]
MakeFile only builds debug version with no errors indicating why.

**Comment by gjulianm** [comment]
It is the default configuration, I have to change it. In the meanwhile, you can run make release to build the release binaries.

-----Message d'origine-----
De : "Ben George" notifications@github.com
Envoyé : ‎24/‎08/‎2016 11:59
À : "hpcn-uam/libstable-opencl" libstable-opencl@noreply.github.com
Objet : [hpcn-uam/libstable-opencl] Only builds debug version (#1)

MakeFile only builds debug version with no errors indicating why.

**Comment by rizwindu** [comment]
Thanks for the quick reply. Do the included matlab wrapper functions work with the opencl version?

**Comment by gjulianm** [comment]
No, the Matlab wrapper was done by Javier Royuela del Val and Federico Simmross Wattenberg in the original library and the OpenCL functions are not included in it. 
On 24 August 2016 at 13:05:29, Ben George (notifications@github.com) wrote:

Thanks for the quick reply. Do the included matlab wrapper functions work with the opencl version?

Best wishes

Ben

Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&amp;utm_medium=email&amp;utm_campaign=sent-from-mailbird]
On 24/08/2016 11:02:07, Guillermo Julián notifications@github.com wrote:
It is the default configuration, I have to change it. In the meanwhile, you can run make release to build the release binaries.

-----Message d'origine-----
De : "Ben George" notifications@github.com
Envoyé : ‎24/‎08/‎2016 11:59
À : "hpcn-uam/libstable-opencl" libstable-opencl@noreply.github.com
Objet : [hpcn-uam/libstable-opencl] Only builds debug version (#1)

MakeFile only builds debug version with no errors indicating why.
